# Generated by Django 5.2.12 on 2026-05-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_appointment_status_doctordayconfig_doctorleave_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctordayconfig',
            unique_together={('doctor', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='doctorleave',
            unique_together={('doctor', 'leave_date')},
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'day_of_week')},
        ),
    ]
